name: DevSecOps Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Python environment
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'

            # Install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            # Run Unit Tests
            - name: Run tests
              run: pytest tests

            # Security Scans
            - name: Trivy Security Scan
              run: bash security/trivy_scan.sh

            - name: Snyk Security Scan
              run: bash security/snyk_scan.sh

        docker:
            runs-on: ubuntu-latest
            needs: build
            steps:
                - name: Checkout code
                  uses: actions/checkout@v3

                - name: Build Docker image
                  run: docker build -t devsecops-app .

                - name: Push to DockerHub
                  env:
                    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  run: |
                    echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
                    docker tag devsecops-app gurucharan27256/devsecops-app:latest
                    docker push gurucharan27256/devsecops-app:latest
